version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: go get github.com/Songmu/ghch/cmd/ghch
      - run: go get github.com/int128/ghcp
      - checkout
      # workaround for https://github.com/golang/go/issues/27925
      - run: sed -e '/^k8s.io\/client-go /d' -i go.sum
      - run: make check
      - run: make
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
